name: Java CI with Maven

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: Decode keystore
        env:
          KEYSTORE: ${{ secrets.TEST_JKS }}
        run: |
            echo "convert key base64 string to file"
            echo "KEYSTORE" >> key.jks.base64
            base64 --decode -i key.jks.base64 -o key.jks
            echo "decode finished"
            ls


  # build:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Set up JDK 17
  #       uses: actions/setup-java@v2
  #       with:
  #         distribution: "adopt"
  #         java-version: "21"

  #     - name: Set up Maven
  #       uses: stCarolas/setup-maven@07fbbe97d97ef44336b7382563d66743297e442f # v4.5
  #       with:
  #         maven-version: 3.9.8
  #     - name: Build with Maven
  #       run: mvn clean verify -Dskip.ui-tests=true
