name: Java CI with Maven

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: macos-latest
    steps:
        # - name: download jre
        #   run: |
        #     mkdir tmp
        #     ls
        #     echo "------------------------------"
        #     cd tmp
        #     mkdir jre
        #     ls
        #     echo "------------------------------"
        #     cd jre
        #     mkdir x86
        #     mkdir aarch64
        #     ls
        #     cd
        #     echo "------------------------------"
        #     ls
        #     echo "------------------------------"
        #     ls work/tycho-example/tycho-example/tmp
        #     echo "------------------------------"
        #     echo "download jre"
        #     curl -L -o work/tycho-example/tycho-example/tmp/jre/x86/jre.tar.gz https://github.com/adoptium/temurin17-binaries/releases/download/jdk-17.0.14%2B7/OpenJDK17U-jre_x64_mac_hotspot_17.0.14_7.tar.gz
        #     echo "download finished"
        #     echo "----------------------------------"
        #     ls work/tycho-example/tycho-example/tmp/jre/x86/
        #     echo "extract archive"
        #     tar -xzf work/tycho-example/tycho-example/tmp/jre/x86/jre.tar.gz -C work/tycho-example/tycho-example/tmp/jre/x86/
        #     echo "extract finished"
        #     echo "--------------------------------"
        #     ls work/tycho-example/tycho-example/tmp/jre/x86/
        #     echo "-------------------------------------"
        #     echo "rename directory"
        #     mv work/tycho-example/tycho-example/tmp/jre/x86/jdk-17.0.14+7-jre work/tycho-example/tycho-example/tmp/jre/x86/jre
        #     echo "rename finished"
        #     echo "------------------------------------"
        #     ls work/tycho-example/tycho-example/tmp/jre/x86/
        #     echo "--------------------------------------"
        #     ls work/tycho-example/tycho-example/tmp/jre/x86/jre/
            
            

    
      - uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: "21"
      - name: Create keystore
        uses: 1arp/create-a-file-action@0.4.5
        with:
          path: test
          isAbsolutePath: false
          file: key.txt
          content: ${{ secrets.MAC_CER_BASE_64 }}
      - name: decode keystore
        run: base64 --decode -i test/key.txt -o test/key.cer
      - name: Check cer location   
        run: ls test
      - name: check cer keystore
        run: openssl x509 -in test/key.cer

          
      # - name: Decode keystore
      #   env:
      #     KEYSTORE: ${{ secrets.KEY_JKS_BASE_64 }}
      #   run: |
      #       echo "convert key base64 string to file"
      #       echo "KEYSTORE" >> key.jks.base64
      #       echo ${{ secrets.KEY_JKS_BASE_64 }} 
      #       base64 --decode -i key.jks.base64 -o /tmp/key.jks
      #       echo "decode finished"
      #       ls /tmp/
      #       keytool -list -v -keystore /tmp/key.jks -storepass 123456


  # build:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Set up JDK 17
  #       uses: actions/setup-java@v2
  #       with:
  #         distribution: "adopt"
  #         java-version: "21"

  #     - name: Set up Maven
  #       uses: stCarolas/setup-maven@07fbbe97d97ef44336b7382563d66743297e442f # v4.5
  #       with:
  #         maven-version: 3.9.8
  #     - name: Build with Maven
  #       run: mvn clean verify -Dskip.ui-tests=true
