name: Java CI with Maven

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: macos-latest
    steps:
        - name: download jre
          run: |
            mkdir tmp
            ls
            echo "------------------------------"
            cd tmp
            mkdir jre
            ls
            echo "------------------------------"
            cd jre
            mkdir x86
            mkdir aarch64
            ls
            cd
            echo "------------------------------"
            ls Desktop
            echo "------------------------------"
            echo "download jre"
            curl -L -o /tmp/jre/x86/  https://github.com/adoptium/temurin17-binaries/releases/download/jdk-17.0.14%2B7/OpenJDK17U-jre_x64_mac_hotspot_17.0.14_7.tar.gz
            echo "download finished"
            echo "----------------------------------"
            ls tmp/jre/x86

    
      # - name: Decode keystore
      #   env:
      #     KEYSTORE: ${{ secrets.TEST_JKS }}
      #   run: |
      #       echo "convert key base64 string to file"
      #       echo "KEYSTORE" >> key.jks.base64
      #       base64 --decode -i key.jks.base64 -o /tmp/key.jks
      #       echo "decode finished"
      #       ls /tmp/


  # build:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Set up JDK 17
  #       uses: actions/setup-java@v2
  #       with:
  #         distribution: "adopt"
  #         java-version: "21"

  #     - name: Set up Maven
  #       uses: stCarolas/setup-maven@07fbbe97d97ef44336b7382563d66743297e442f # v4.5
  #       with:
  #         maven-version: 3.9.8
  #     - name: Build with Maven
  #       run: mvn clean verify -Dskip.ui-tests=true
