on:
  push:

jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: checkout test
        uses: actions/checkout@v6
      - name: Set env
        run: |
          echo "RELEASE_VERSION=$(echo ${GITHUB_REF#refs/*/} | cut -c 2-)" >> $GITHUB_ENV
      - name: Test
        run: echo $RELEASE_VERSION

  build:
    runs-on: macos-latest
    steps:

    - name: checkout
      uses: actions/checkout@v6
    - name: List files in the repository
      run: |
          ls ${{ github.workspace }}
    - name: Set up JDK 17
      uses: actions/setup-java@v6
      with:
        distribution: 'adopt'
        java-version: '21'
    
    - name: check jks loc
      run: ls ${{ github.workspace }}/keystore
    - name: build
      run: |
            ls /Users/runner/work/tycho-example/tycho-example/
            echo "--------------------------------"
            echo "create temp dirs for jre"
            mkdir ${{ github.workspace }}/jre
            cd jre
            mkdir x86
            mkdir aarch64
            cd
            echo "----------------------------------"
            echo "download jre"
            curl -L -o ${{ github.workspace }}/jre/x86/jre.tar.gz https://github.com/adoptium/temurin17-binaries/releases/download/jdk-17.0.14%2B7/OpenJDK17U-jre_x64_mac_hotspot_17.0.14_7.tar.gz
            echo "download finished"
            echo "----------------------------------"
            echo "extract archive"
            tar -xzf ${{ github.workspace }}/jre/x86/jre.tar.gz -C ${{ github.workspace }}/jre/x86/
            echo "extract finished"
            echo "-------------------------------------"
            echo "rename directory"
            mv ${{ github.workspace }}/jre/x86/jdk-17.0.14+7-jre ${{ github.workspace }}/jre/x86/jre
            echo "rename finished"
            echo "------------------------------------"
            echo "list jre loc"
            ls ${{ github.workspace }}/jre/x86
            echo "--------------------------------------"
            cd ${{ github.workspace }}
            mvn verify -DskipTests
            echo "--------------------------------------"
            echo "list macos build"
            ls ${{ github.workspace }}/releng/com.vogella.tycho.product/target/products/com.vogella.tycho.product/macosx/cocoa/x86_64/Eclipse.app/Contents/Eclipse


    - name: compress macos build
      run: |
        cd /Users/runner/work/tycho-example/tycho-example/releng/com.vogella.tycho.product/target/products/com.vogella.tycho.product/macosx/cocoa/x86_64/
        tar -cf ${{ github.workspace }}/releng/com.vogella.tycho.product/target/products/com.vogella.tycho.product-macosx.cocoa.x86_64.tar.gz Eclipse.app
      
    - name: check release ver
      run: echo ${{ github.ref_name }}

    - name: Create GitHub Release and Upload Assets
      uses: softprops/action-gh-release@718ea10b132b3b2eba29c1007bb80653f286566b #v3.0.0
      with:
        tag_name: v7.7.7
        name: Release 7.7.7
        draft: false
        prerelease: false
        files: |
            ${{ github.workspace }}/releng/com.vogella.tycho.product/target/products/com.vogella.tycho.product-linux.gtk.x86_64.tar.gz
            ${{ github.workspace }}/releng/com.vogella.tycho.product/target/products/com.vogella.tycho.product-macosx.cocoa.x86_64.tar.gz
            ${{ github.workspace }}/releng/com.vogella.tycho.product/target/products/com.vogella.tycho.product-win32.win32.x86_64.zip

    - name: List files in the repository after build
      run: |
          ls /Users/runner/work/tycho-example/tycho-example/releng/com.vogella.tycho.product/target/products
