name: Release Workflow

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: checkout test
        uses: actions/checkout@v4
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Test
        run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}

  build:
    runs-on: macos-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: List files in the repository
      run: |
          ls ${{ github.workspace }}
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: 17
    - name: Compile code
      run: mvn -B verify --file pom.xml


    
